package spaceinvaders.frontend;

import javax.swing.ImageIcon;

/**
 *
 * @author saien
 */
public class Principal extends javax.swing.JFrame {
    private String PATH_BACKGROUND_GIF = "spaceinvaders/Images";
    private ImageIcon img = new ImageIcon(PATH_BACKGROUND_GIF);
    public Principal() {
        initComponents();
        
        btn_NewGame.setBorderPainted(false);
        btn_NewGame.setFocusPainted(false);
        
        btn_Continuar.setBorderPainted(false);
        btn_Continuar.setFocusPainted(false);
        
        btn_PuntajeMaximo.setBorderPainted(false);
        btn_PuntajeMaximo.setFocusPainted(false);
        
        btn_Salir.setBorderPainted(false);
        btn_Salir.setFocusPainted(false);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenuPrincipal = new javax.swing.JPanel();
        btn_NewGame = new javax.swing.JButton();
        btn_Continuar = new javax.swing.JButton();
        btn_PuntajeMaximo = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMenuPrincipal.setBackground(new java.awt.Color(0, 0, 0));

        btn_NewGame.setBackground(new java.awt.Color(0, 0, 0));
        btn_NewGame.setForeground(new java.awt.Color(255, 255, 255));
        btn_NewGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceinvaders/Images/btn_NewGame.png"))); // NOI18N
        btn_NewGame.setBorder(null);
        btn_NewGame.setBorderPainted(false);
        btn_NewGame.setContentAreaFilled(false);
        btn_NewGame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_NewGame.setOpaque(true);

        btn_Continuar.setBackground(new java.awt.Color(0, 0, 0));
        btn_Continuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceinvaders/Images/btn_Continuar.png"))); // NOI18N
        btn_Continuar.setBorder(null);
        btn_Continuar.setBorderPainted(false);
        btn_Continuar.setContentAreaFilled(false);
        btn_Continuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_PuntajeMaximo.setBackground(new java.awt.Color(0, 0, 0));
        btn_PuntajeMaximo.setForeground(new java.awt.Color(255, 255, 255));
        btn_PuntajeMaximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceinvaders/Images/btn_Puntajes.png"))); // NOI18N
        btn_PuntajeMaximo.setBorder(null);
        btn_PuntajeMaximo.setBorderPainted(false);
        btn_PuntajeMaximo.setContentAreaFilled(false);
        btn_PuntajeMaximo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_Salir.setBackground(new java.awt.Color(0, 0, 0));
        btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceinvaders/Images/btn_Salir.png"))); // NOI18N
        btn_Salir.setBorder(null);
        btn_Salir.setBorderPainted(false);
        btn_Salir.setContentAreaFilled(false);
        btn_Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spaceinvaders/Images/titulo.png"))); // NOI18N

        javax.swing.GroupLayout pnlMenuPrincipalLayout = new javax.swing.GroupLayout(pnlMenuPrincipal);
        pnlMenuPrincipal.setLayout(pnlMenuPrincipalLayout);
        pnlMenuPrincipalLayout.setHorizontalGroup(
            pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuPrincipalLayout.createSequentialGroup()
                .addGroup(pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE))
                    .addGroup(pnlMenuPrincipalLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_PuntajeMaximo)
                            .addComponent(btn_NewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuPrincipalLayout.createSequentialGroup()
                        .addComponent(btn_Salir)
                        .addGap(208, 208, 208))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuPrincipalLayout.createSequentialGroup()
                        .addComponent(btn_Continuar)
                        .addGap(179, 179, 179))))
        );
        pnlMenuPrincipalLayout.setVerticalGroup(
            pnlMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuPrincipalLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(btn_NewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(btn_Continuar)
                .addGap(18, 18, 18)
                .addComponent(btn_PuntajeMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Salir)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Continuar;
    private javax.swing.JButton btn_NewGame;
    private javax.swing.JButton btn_PuntajeMaximo;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlMenuPrincipal;
    // End of variables declaration//GEN-END:variables
}
